config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'categories' => 'categories#index'

  resources :topics
  resources :posts

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics

  def self.get_project_name
    "FORUM"
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
       devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :avatar) }
       devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
   end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @topic = Topic.find(@post.topic_id)

    @post.save!
    redirect_to @topic
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save!
      render :show
    else
      render :new
    end
  end

  def show
    @topic ||= Topic.find(params[:id])
    @post = Post.new
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <p>
    <h2><%= category.name %></h2>
    <!-- Niech tylko zalogowany użytkownik będzie mógł założyć nowy topic-->
    <%- if user_signed_in? %>
      <%= link_to "Create new topic", new_topic_path(category_id: "#{category.id}") %>
    <% end %>
    <!-- Wyświetlmy wszystkie topici dla każdej z kategorii  -->
    <%- category.topics.each do |topic| %>
      <p>
        <!-- jak napiszemy linkt_to 'topic' railsy ogarną że chodzi nam o 'topics_path/topic.id" MAGIA!!!!!! -->
        <%= link_to "#{topic.name}",  topic %>
      </p>
    <% end %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1> <%= link_to "#{Category.get_project_name}", root_path %></h1>
<%- if user_signed_in? %>
  <%= current_user.email %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <div class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>
  <!-- Udało mi się rozwszyfrować syntax :) -->
  <!-- Dodając hidden_field do form_fora dla obiektu @topic sprawiamy iż w paramsach będzie można znaleźć zapis : -->
  <!-- "topic"=>{"name"=>"ABC", "category_id"=>"2"} -->
  <!-- Czyli dokładnie to o co nam chodziło, teraz trzeba pamiętać aby whitelistować parametry 'name' oraz 'category_id' w kontrolerze -->
  <%= f.hidden_field :category_id, :value => "#{params["category_id"]}" %>
  <div class="button">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1> Create new topic </h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<!-- jak to na forum, trzeba wyśiwtlić dotychczasowe posty -->
<% @topic.posts.each do |post| %>
  <h3> <%= post.user.email %> <%= image_tag post.user.avatar.url(:thumb) %></h3>
  <p>
    <%= post.content %>
  </p>
<% end %>

<!-- zeby można było urzyć @post musieliśmy dodać w topics_controller (bo w jego widoku jesteśmy) -->
<!-- do akcji show ... bo w takim widoku jesteśmy .. zmienną współdzieloną @post -->
<!-- dodatkowo, dodawanie postów jest mozliwe tylko dla zalogowanych użytkowników -->
<%- if user_signed_in? %>
  <%= form_for(@post) do |f| %>
    <div class="field">
      <%= f.label :content %> <br>
      <%= f.text_area :content %>
      <!-- Wykorzystamy nowo poznaną sztuczkę :)))) -->
      <%= f.hidden_field :topic_id, :value => "#{@topic.id}" %>
      <%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
    </div>
    <div class="button">
      <%= f.submit "Send your response" %>
    </div>
  <% end %>
<% end %>